
 <div class="uk-card-default bg-gradient-grey p-4 uk-light uk-hidden@s">
        <div class="uk-flex uk-flex-between uk-flex-middle">
            <h4 class="mb-0">  Introduction to HTML </h4>
            <i class="icon-feather-video icon-small"  uk-toggle="target: #open-side-course"></i>
        </div>
    </div>


    <div class="section-small bg-white uk-visible@s">
        <div class="px-5">

            <div class="uk-flex-middle" uk-grid>

                <div class="uk-width-expand@m">

                    <div uk-grid>

                        <div class="uk-width-2-3@m">
                            <br>
                            <a href="<?php echo $this->basePath('/courses');?>" class="uk-text-muted">
                                <i class="icon-line-awesome-long-arrow-left"></i> back to list
                            </a>
                        </div>

                    </div>
                </div>
            </div>

        </div>

        <hr>


        <!-- Toggle sidebar button -->

        <div class="uk-position-center-left uk-margin-medium-left">

            <button type="button" class="btn btn-primary rounded-circle btn-icon-only icon-xsmall" uk-toggle="target: #open-side-course">
                <span class="btn-inner--icon">
                  <i class="uil-list-ul"></i>
                </span>
              </button>

        </div>

        <!-- course section title -->
        <div class="uk-container-small uk-margin-auto uk-margin-medium-top">
            <h3 class=" uk-text-light"> Module: <?php echo $this->active_module->getName()?> </h3>
            <h5 class=" uk-text-light"> Topic: <?php echo $this->active_video->getTitle()?> </h5>
        </div>

    </div>


    <div class="uk-container-small uk-padding-small uk-margin-auto">
        <div class="embed-video uk-animation-fade">
            <iframe src="<?php echo $this->basePath('/courses/play-video/' . $this->active_video->getId()) ?>" frameborder="0" allowfullscreen
                uk-responsive></iframe>
        </div>
        <br/>
        <div class="row">
            <div class="col-lg-12">
                <?php 
                    $key = 'video-' . $this->active_video->getId() . '-module-' . $this->active_module->getId();
                    $nextLink = current(array_slice($this->page_track, array_search($key, array_keys($this->page_track)) + 1, 1));
                    $hasPrevious = array_search($key, array_keys($this->page_track)) - 1 < 0 ? false : true;
                    $previousLink = current(array_slice($this->page_track, array_search($key, array_keys($this->page_track)) - 1, 1));
                ?>
                <?php
                if( $previousLink && $hasPrevious ) :
                ?>
                    <a href="<?php echo $this->basePath('/courses/course/' . $this->course_id . '/module/' . $previousLink['module'] . '/video/' . $previousLink['video']); ?>" style="float:left;" class="btn btn-default icon-label">Previous</a>
                <?php 
                endif;
                if( $nextLink ) :
                ?>
                    <a href="<?php echo $this->basePath('/courses/course/' . $this->course_id . '/module/' . $nextLink['module'] . '/video/' . $nextLink['video']); ?>" style="float:right;" class="btn btn-default icon-label">Next</a>
                <?php 
                else:
                ?>
                    <a href="<?php echo $this->basePath('/quiz/index/' . $this->course_id); ?>" style="float:right;" class="btn btn-default icon-label">
                        <span class="inner-text"> Finish </span>
                    </a>
                    
                <?php 
                endif;
                ?>
            </div>
        </row>
    </div>


    <!-- Sidebar-->
    <div id="open-side-course" uk-offcanvas="overlay: true">
        <div class="uk-offcanvas-bar p-0 uk-overflow-hidden">
            <button class="uk-offcanvas-close" type="button" uk-close></button>
            <h6 class="bg-gradient-grey text-white py-4 p-3 mb-0"></h6>

            <ul class="uk-child-width-expand mb-0"
                uk-switcher="animation: uk-animation-slide-right-small, uk-animation-slide-left-small" uk-tab>
                <li class="uk-active"><a href="#"> Contents</a></li>
                
            </ul>

            <?php
                $courses = $this->courses;
                unset($courses['course']);
                if($courses) :
                    foreach($courses as $course) :
            ?>
           
           
            <ul class="uk-switcher uk-overflow-hidden">
                 <?php
                $courses = $this->courses;
                unset($courses['course']);
                if($courses) :
                    $count = 0;
                    foreach($courses as $moduleId=>$course) :
                        $class = $this->active_module->getId() == $moduleId ? 'uk-open' : '';
                        $count++;
            ?>
                <!-- first tab -->

                <li>
                    <div class="vidlist-3-content" data-simplebar>
                        <ul class="vidlist-3-section" uk-accordion>


                            <!--  section 1  -->
                            <li class="<?php echo $class; ?>">
                                <a class="uk-accordion-title" href="#"> <h5><?php echo $course['name'] ?></h5> </a>
                                <div class="uk-accordion-content">
                                    <!-- vidlist -->
                                     <?php 
                                        if($course) :
                                            $videoClass = '';
                                            foreach($course['videos'] as $video) :
                                                $videoClass = $this->active_video->getId() == $video->getId() ? 'uk-active' : '';
                                    ?>
                                            
                                   
                                    <ul class="vidlist-3"
                                        >
                                       
                                        <li class="<?php echo $videoClass ?>">
                                            <a href="<?php echo $this->basePath('/courses/course/' . $this->course_id . '/module/' . $moduleId . '/video/' . $video->getId()); ?>"><?php echo $video->getTitle() ?> </a>
                                        </li>
                                      
                                       
                                    </ul>
                                     <?php
                                            endforeach;
                                        endif;
                                    ?>
                                </div>
                            </li>   
                             <?php 
                endforeach;
            endif;
            ?>          
            </ul>

            <?php 
                endforeach;
            endif;
            ?>
        </div>
    </div>


    <!-- For Night mode -->
    <script>
        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' night-mode';
            }
        })(window, document);


        (function (window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('night-mode');
                if (document.documentElement.classList.contains('night-mode')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>

