<!doctype html>
<html lang="en">

<head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Courses')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])        
            ->prependStylesheet($this->basePath('css/icons.css'))  
            ->prependStylesheet($this->basePath('css/bootstrap.css'))  
            ->prependStylesheet($this->basePath('css/framework.css'))
            ->prependStylesheet($this->basePath('css/night-mode.css'))
            ->prependStylesheet($this->basePath('css/style.css')) 
            ->prependStylesheet($this->basePath('css/result.css'))    
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/framework.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
            ->prependFile($this->basePath('js/simplebar.js'))
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/bootstrap-select.min.js'))
        ?>
    </head>

<body>

    <!-- Wrapper -->
    <div id="wrapper" class="bg-white">

        <!-- Header Container
        ================================================== -->
        <header class="header header-horizontal header bg-grey uk-light">

            <div class="container">
                <nav uk-navbar>

                    <!-- left Side Content -->
                    <div class="uk-navbar-left">

                        <!-- menu icon -->
                        <span class="mmenu-trigger">
                            <button class="hamburger hamburger--collapse" type="button">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                        </span>

                        <!-- logo -->
                        <a href="dashboard.html" class="logo">
                            <img src="/images/logo-dark.svg" alt="">
                            <span> Skilltik</span>
                        </a>

                        <!-- Main Navigation -->

                        <nav id="navigation">
                            <ul id="responsive">
                                <li><a href="#">Home</a> </li>
                                <li><a href="course-path.html" class="nav-active">Track</a> </li>
                                <li><a href="book.html">Book</a> </li>
                                <li><a href="<?php echo $this->basePath('/login'); ?>">Login</a> </li>
                            </ul>
                        </nav>
                        <!-- Main Navigation / End -->

                    </div>

                    <?php 
                    if($this->currentUser()) :
                    ?>
                    <!--  Right Side Content   -->

                        <div class="uk-navbar-right">

                            <div class="header-widget">

                                <div class="searchbox uk-visible@s">

                                    <input class="uk-search-input" type="search" placeholder="Search...">
                                    <button class="btn-searchbox"> </button>

                                </div>
                                <!-- Search box dropdown -->
                                <div uk-dropdown="pos: top;mode:click;animation: uk-animation-slide-bottom-small"
                                    class="dropdown-search">
                                    <div class="erh BR9 MIw"
                                        style="top: -27px;position: absolute ; left: 24px;fill: currentColor;height: 24px;pointer-events: none;color: #f5f5f5;">
                                        <svg width="22" height="22">
                                            <path d="M0 24 L12 12 L24 24"></path>
                                        </svg></div>
                                    <!-- User menu -->

                                    <ul class="dropdown-search-list">
                                        <li class="list-title">
                                            Recent Searches
                                        </li>
                                        <li>
                                            <a href="course-intro.html">
                                                Ultimate Web Designer And Developer Course</a>
                                        </li>
                                        <li><a href="course-intro.html">
                                                The Complete Ruby on Rails Developer Course </a>
                                        </li>
                                        <li><a href="course-intro.html">
                                                Bootstrap 4 From Scratch With 5 Real Projects </a>
                                        </li>
                                        <li> <a href="course-intro.html">
                                                The Complete 2020 Web Development Bootcamp </a>
                                        </li>
                                        <li class="menu-divider">
                                        <li><a href="course-intro.html">
                                                Bootstrap 4 From Scratch With 5 Real Projects </a>
                                        </li>
                                        <li> <a href="course-intro.html">
                                                The Complete 2020 Web Development Bootcamp </a>
                                        </li>
                                    </ul>

                                </div>



                                <!-- User icons close mobile-->
                                <span class="icon-feather-x icon-small uk-hidden@s"
                                    uk-toggle="target: .header-widget ; cls: is-active"> </span>


                                <a href="#" class="header-widget-icon"
                                    uk-tooltip="title: My Courses ; pos: bottom ;offset:21">
                                    <i class="uil-youtube-alt"></i>
                                </a>

                                <!-- courses dropdown List -->
                                <div uk-dropdown="pos: top;mode:click;animation: uk-animation-slide-bottom-small"
                                    class="dropdown-notifications my-courses-dropdown">

                                    <!-- notivication header -->
                                    <div class="dropdown-notifications-headline">
                                        <h4>Your Courses</h4>
                                        <a href="#">
                                            <i class="icon-feather-settings"
                                                uk-tooltip="title: Notifications settings ; pos: left"></i>
                                        </a>
                                    </div>

                                    <!-- notification contents -->
                                    <div class="dropdown-notifications-content" data-simplebar>

                                        <!-- notiviation list -->
                                        <ul>
                                            <li class="notifications-not-read">
                                                <a href="course-intro.html">
                                                    <span class="notification-image">
                                                        <img src="/images/course/1.png" alt=""> </span>
                                                    <span class="notification-text">
                                                        <span class="course-title">Ultimate Web Designer & Web Developer
                                                        </span>
                                                        <span class="course-number">6/35 </span>
                                                        <span class="course-progressbar">
                                                            <span class="course-progressbar-filler"
                                                                style="width:95%"></span>
                                                        </span>
                                                    </span>

                                                    <!-- option menu -->
                                                    <span class="btn-option">
                                                        <i class="icon-feather-more-vertical"></i>
                                                    </span>
                                                    <div class="dropdown-option-nav"
                                                        uk-dropdown="pos: bottom-right ;mode : hover">
                                                        <ul>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-material-outline-dashboard"></i>
                                                                    Course Dashboard</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-video"></i>
                                                                    Resume Course</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-x"></i>
                                                                    Remove Course</span>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </a>

                                            </li>
                                            <li>
                                                <a href="course-intro.html">
                                                    <span class="notification-image">
                                                        <img src="/images/course/3.png" alt=""> </span>
                                                    <span class="notification-text">
                                                        <span class="course-title">The Complete JavaScript Course Build Real
                                                            Projects !</span>
                                                        <span class="course-number">6/35 </span>
                                                        <span class="course-progressbar">
                                                            <span class="course-progressbar-filler"
                                                                style="width:95%"></span>
                                                        </span>
                                                    </span>

                                                    <!-- option menu -->
                                                    <span class="btn-option">
                                                        <i class="icon-feather-more-vertical"></i>
                                                    </span>
                                                    <div class="dropdown-option-nav"
                                                        uk-dropdown="pos: bottom-right ;mode : hover">
                                                        <ul>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-material-outline-dashboard"></i>
                                                                    Course Dashboard</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-video"></i>
                                                                    Resume Course</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-x"></i>
                                                                    Remove Course</span>
                                                            </li>
                                                        </ul>
                                                    </div>

                                                </a>
                                            </li>
                                            <li>
                                                <a href="course-intro.html">
                                                    <span class="notification-image">
                                                        <img src="/images/course/2.png" alt=""> </span>
                                                    <span class="notification-text">
                                                        <span class="course-title">Learn Angular Fundamentals From The
                                                            Beginning</span>
                                                        <span class="course-number">6/35 </span>
                                                        <span class="course-progressbar">
                                                            <span class="course-progressbar-filler"
                                                                style="width:95%"></span>
                                                        </span>
                                                    </span>

                                                    <!-- option menu -->
                                                    <span class="btn-option">
                                                        <i class="icon-feather-more-vertical"></i>
                                                    </span>
                                                    <div class="dropdown-option-nav"
                                                        uk-dropdown="pos: bottom-right ;mode : hover">
                                                        <ul>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-material-outline-dashboard"></i>
                                                                    Course Dashboard</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-video"></i>
                                                                    Resume Course</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-x"></i>
                                                                    Remove Course</span>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="course-intro.html">
                                                    <span class="notification-image">
                                                        <img src="/images/course/1.png" alt=""> </span>
                                                    <span class="notification-text">
                                                        <span class="course-title">Ultimate Web Designer & Web Developer
                                                        </span>
                                                        <span class="course-number">6/35 </span>
                                                        <span class="course-progressbar">
                                                            <span class="course-progressbar-filler"
                                                                style="width:95%"></span>
                                                        </span>
                                                    </span>

                                                    <!-- option menu -->
                                                    <span class="btn-option">
                                                        <i class="icon-feather-more-vertical"></i>
                                                    </span>
                                                    <div class="dropdown-option-nav"
                                                        uk-dropdown="pos: top-right ;mode : hover">
                                                        <ul>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-material-outline-dashboard"></i>
                                                                    Course Dashboard</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-video"></i>
                                                                    Resume Course</span>
                                                            </li>
                                                            <li>
                                                                <span>
                                                                    <i class="icon-feather-x"></i>
                                                                    Remove Course</span>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </a>
                                            </li>
                                        </ul>

                                    </div>
                                    <div class="dropdown-notifications-footer">
                                        <a href="#"> sell all</a>
                                    </div>
                                </div>

                                <!-- notificiation icon  -->

                                
                                <!-- Message  -->

                                
                                <!-- Message  notificiation dropdown -->
                                
                                <!-- profile-icon-->

                                <a href="#" class="header-widget-icon profile-icon">
                                    <img src="/images/avatars/avatar-2.jpg" alt="" class="header-profile-icon">
                                </a>

                                <div uk-dropdown="pos: top-right ;mode:click" class="dropdown-notifications small">

                                    <!-- User Name / Avatar -->
                                    <a href="profile-1.html">

                                        <div class="dropdown-user-details">
                                            <div class="dropdown-user-avatar">
                                                <img src="/images/avatars/avatar-2.jpg" alt="">
                                            </div>
                                            <div class="dropdown-user-name">
                                            <?php echo $this->currentUser()->getName(); ?>
                                            </div>
                                        </div>

                                    </a>

                                    <!-- User menu -->

                                    <ul class="dropdown-user-menu">
                                        <li>
                                            <a href="#">
                                                <i class="icon-material-outline-dashboard"></i> Dashboard</a>
                                        </li>
                                        <li><a href="#">
                                                <i class="icon-feather-bookmark"></i> Bookmark </a>
                                        </li>
                                        <li><a href="profile-edit.html">
                                                <i class="icon-feather-settings"></i> Account Settings</a>
                                        </li>
                                        <li><a href="#" style="color:#62d76b">
                                                <i class="icon-feather-star"></i> Upgrade To Premium</a>
                                        </li>
                                        <li>
                                            <a href="#" id="night-mode" class="btn-night-mode">
                                                <i class="icon-feather-moon"></i> Night mode
                                                <span class="btn-night-mode-switch">
                                                    <span class="uk-switch-button"></span>
                                                </span>
                                            </a>
                                        </li>
                                        <li class="menu-divider">
                                        <li><a href="#">
                                                <i class="icon-feather-help-circle"></i> Help</a>
                                        </li>
                                        <li><a href="/logout">
                                                <i class="icon-feather-log-out"></i> Sign Out</a>
                                        </li>
                                    </ul>


                                </div>


                            </div>



                            <!-- icon search-->
                            <a class="uk-navbar-toggle uk-hidden@s"
                                uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#">
                                <i class="uil-search icon-small"></i>
                            </a>

                            <!-- User icons -->
                            <a href="#" class="uil-user icon-small uk-hidden@s"
                                uk-toggle="target: .header-widget ; cls: is-active">
                            </a>

                        </div>
                        <!-- End Right Side Content / End -->

                    <?php 
                    endif;
                    ?>
                </nav>

            </div>
            <!-- container  / End -->

        </header>

        <!-- overlay seach on mobile-->
        <div class="nav-overlay uk-navbar-left uk-position-relative uk-flex-1 bg-grey uk-light p-2" hidden
            style="z-index: 10000;">
            <div class="uk-navbar-item uk-width-expand" style="min-height: 60px;">
                <form class="uk-search uk-search-navbar uk-width-1-1">
                    <input class="uk-search-input" type="search" placeholder="Search..." autofocus>
                </form>
            </div>
            <a class="uk-navbar-toggle" uk-close uk-toggle="target: .nav-overlay; animation: uk-animation-fade"
                href="#"></a>
        </div>



        <div class="page-content">
            <?= $this->content; ?>
            <?= $this->inlineScript() ?>
        </div>

        <!-- footer
        ================================================== -->
        <div class="footer">
            <div class="container">
                <div uk-grid>
                    <div class="uk-width-1-3@m">
                        <a href="home.html" class="uk-logo">
                            <!-- logo icon -->
                            <i class="uil-graduation-hat"> </i>
                            Skilltik
                        </a>
                        <p class="footer-description">Skilltik delivers a varied range of high-quality 
                        online training courses and strictly adhere to a code of best practice. Specializing 
                        in health and safety, food safety, safeguarding people and business</p>
                    </div>
                    <div class="uk-width-expand@s uk-width-1-2">
                        <div class="footer-links pl-lg-8">
                            <h5>Explore </h5>
                            <ul>
                                <li><a href="course-card.html"> Courses </a></li>
                                <li><a href="course-path.html"> Track </a></li>
                                <li><a href="blog-card.html"> Blog </a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="uk-width-expand@s uk-width-1-2">
                        <div class="footer-links pl-lg-8">
                            <h5> Account </h5>
                            <ul>
                                <li><a href="profile-1.html"> Profile </a></li>
                                <li><a href="#"> Settings </a></li>
                                <li><a href="#"> Projects </a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="uk-width-expand@s uk-width-1-2">
                        <div class="footer-links pl-lg-8">
                            <h5> Resources</h5>
                            <ul>
                                <li><a href="#"> Contact </a></li>
                                <li><a href="page-Privacy.html"> Privacy Policy </a></li>
                                <li><a href="page-term.html"> Terms of Use </a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="uk-grid-collapse" uk-grid>
                    <div class="uk-width-expand@s uk-first-column">
                        <p>© 2021 <strong>Skilltik</strong>. All Rights Reserved. </p>
                    </div>
                    <div class="uk-width-auto@s">
                        <nav class="footer-nav-icon">
                            <ul>
                                <li><a href="#"><i class="icon-brand-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-brand-dribbble"></i></a></li>
                                <li><a href="#"><i class="icon-brand-youtube"></i></a></li>
                                <li><a href="#"><i class="icon-brand-twitter"></i></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- For Night mode -->
    <script>
        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' night-mode';
            }
        })(window, document);


        (function (window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('night-mode');
                if (document.documentElement.classList.contains('night-mode')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>

</body>

</html>