
<div style="width:750px; height:600px; padding:20px; text-align:center; border: 5px solid #787878">
       <span style="font-size:50px; font-weight:bold">Certificate of Completion</span>
       <br><br>
       <span style="font-size:25px"><i>This is to certify that</i></span>
       <br><br>
       <span style="font-size:30px"><b><?php echo $this->name ?></b></span><br/><br/>
       <span style="font-size:25px"><i>has completed the course</i></span> <br/><br/>
       <span style="font-size:30px"><?php echo $this->course_title; ?></span> <br/><br/>
       <span style="font-size:20px">with score of <b><?php echo $this->percentage ?>%</b></span> <br/><br/><br/><br/>
       <span style="font-size:25px"><i>dated</i></span><br>
      
      <span style="font-size:30px"><?php echo date('l jS \of F Y', strtotime($this->date)); ?> </span>
   <br/>
   <br/>
   <br/>
   <br/>
   <br/>
</div>
